# DEFAULTS
# ========

safe:        false
auto:        true
server:      false

# SITE VARS
# =========

title: Allmänna kontoret
subtitle: "På Arkitekturmuseet<br>30 okt - 30 nov, 2012"
times: "10h to 18h"
amuseettitle: Allmänna kontoret på Arkitekturmuseet
baseurl:    http://allmannakontoret.se
assetsurl:    http://allmannakontoret.se
bannername: Arkitekturmuseet
amusseet-site: Allmänna kontorets huvudsida


prose: "http://prose.io/#dilettant/allmannakontoret/edit/gh-pages"
repo : "_posts/amuseet/"
githubrepourl: "https://github.com/dilettant/allmannakontoret" 
flattrurl: "https://flattr.com/thing/945925/Allmnna-kontoret"

lang: sv
gravasize: 142

# MENUS
# =====

# MAIN
# -----
menu_main:
  - hem
  - om_projektet
  - koncept
  - kontakt

# ABOUT
# -----
menu_om_projektet:
  - team
  - filosofi:
    - kooperation
    - offentlighet
    - mangfald
    - open_source
  - delmoment:
    - delmoment_1
    - delmoment_2

# CONCEPT
# ------
menu_koncept:
  - sammanfattning
  - utgangspunkter_och_perspektiv:
    - forandringar_pa_arbetsmarknaden
    - offentliga_motesplatser_och_ratten_till_arbete
    - betydelsen_av_offentliga_motesplatser_i_lokal_utveckling
  - visionen_om_allmanna_kontor:
    - allmanna_kontoret_i_praktiken
    - brukargrupper
    - agarformer_och_riktlinjer
    - finansieringsformer
    - utformning_och_innehall
  - forslag_pa_verksamhetsformer:
    - etablering_av_ny_verksamhet
    - anvandning_av_tillfalligt_oanvanda_lokaler
    - utokat_uppdrag_for_existerande_institutioner
  - allmanna_kontoret_som_politisk_fraga:
    - arbetsmarknad
    - kultur
    - naringsliv
    - utbildning


# DICTIONARY
# ==========

index: Hem
om_projektet : Om projektet
offentlighet : Offentlighet
mangfald : Mångfald
delmoment_I : Delmoment 1
delmoment_II : Delmoment 2
sammanfattning : Sammanfattning
utgangspunkter_och_perspektiv : Utgångspunkter och perspektiv
forandringar_pa_arbetsmarknaden : Förändringar på arbetsmarknaden
offentliga_motesplatser_och_ratten_till_arbete : Offentliga mötesplatser och rätten till arbete
betydelsen_av_offentliga_motesplatser_i_lokal_utveckling : Betydelsen av offentliga mötesplatser i lokal utveckling
visionen_om_allmanna_kontor : Visionen om allmänna kontor
allmanna_kontoret_i_praktiken : Allmänna kontoret i praktiken
brukargrupper : Brukargrupper
agarformer_och_riktlinjer : Ägarformer och riktlinjer
utformning_och_innehall : Utformning och innehåll
forslag_pa_verksamhetsformer : Förslag på verksamhetsformer
etablering_av_ny_verksamhet : Etablering av ny verksamhet
anvandning_av_tillfalligt_oanvanda_lokaler : Användning av tillfälligt oanvända lokaler
utokat_uppdrag_for_existerande_institutioner : Utökat uppdrag for existerande institutioner
allmanna_kontor_som_politisk_fraga : Allmänna kontor som politisk fråga
arbetsmarknad : Arbetsmarknad
naringsliv : Näringsliv
utbildning : Utbildning
om_projektet: Om projektet
finansieringsformer: Finansieringsformer