# DEFAULTS
# ========

safe:        false
auto:        true
server:      false

# SITE VARS
# =========

title: Allmänna kontoret
subtitle: "På Arkitekturmuseet<br>30 okt - 30 nov, 2012"
description: "The Public Office is a long-term development project that seeks to articulate an idea of open and rent-free work and meeting places, where the public is given the opportunity to engage in work and further education. During several project phases, we explore the concept’s possibilities and potential functions in an increasingly mobile labor market, as well as in urban planning and local community development, business development and integration."
author: "http://dilettant.se"
copyright: "This site is open source and is proudly hosted on GitHub."

amuseettitle: Allmänna kontoret på Arkitekturmuseet
dates: "30 OCT - 30 NOV 2012"
times: "Tisdag-Lördag kl 10.00-18.00"
join: "Kom till Allmänna kontoret på Arkitekturmuseet"
more: "Läs mer"
baseurl: http://allmannakontoret.se
assetsurl: http://allmannakontoret.se
bannername: arkitekturmuseet

prose: "http://prose.io/#dilettant/allmannakontoret/edit/gh-pages"
mainrepo : "_posts"
repo : "_posts/amuseet/"
githubrepourl: "https://github.com/dilettant/allmannakontoret#allmänna-kontoret" 
flattrurl: "https://flattr.com/thing/945925/allmannakontoret"

lang: sv
gravasize: 60

# MENUS
# =====

# MAIN
# -----
menu_main:
  - hem
  - om_projektet
  - koncept
  - kontakt

# ABOUT
# -----
menu_om_projektet:
  - team
  - filosofi:
    - Kooperation
    - allmanning
    - mangfald
    - Open_Source
  - delmoment:
    - Delmoment_I
    - Delmoment_II
    - Delmoment_III

# CONCEPT
# ------
menu_koncept:
  - sammanfattning
  - utgangspunkter_och_perspektiv:
    - forandringar_pa_arbetsmarknaden
    - offentliga_motesplatser_och_ratten_till_arbete
    - betydelsen_av_offentliga_motesplatser_i_lokal_utveckling
    - arbete,_halsa_och_miljo
  - visionen_om_allmanna_kontor:
    - allmanna_kontoret_i_praktiken
    - Brukargrupper
    - agarformer_och_riktlinjer
    - Finansieringsformer
    - utformning_och_innehall
  - forslag_pa_verksamhetsformer:
    - Etablering_av_ny_verksamhet
    - anvandning_av_tillfalligt_oanvanda_lokaler
    - utokat_uppdrag_for_existerande_institutioner
  - allmanna_kontoret_som_politisk_fraga:
    - Arbetsmarknad
    - Kultur
    - naringsliv
    - Utbildning


# DICTIONARY
# ==========

welcome: Välkommen
support: Stöd oss
connect: Följ oss
swedish: Svenska
english: Engelska
newsletter: Nyhetsbrev
index: Hem
allmanning : Allmänning
mangfald : Mångfald
utgangspunkter_och_perspektiv : Utgångspunkter och perspektiv
forandringar_pa_arbetsmarknaden : Förändringar på arbetsmarknaden
offentliga_motesplatser_och_ratten_till_arbete : Offentliga mötesplatser och rätten till arbete
betydelsen_av_offentliga_motesplatser_i_lokal_utveckling : Betydelsen av offentliga mötesplatser i lokal utveckling
visionen_om_allmanna_kontor : Visionen om allmänna kontor
allmanna_kontoret_i_praktiken : Allmänna kontoret i praktiken
agarformer_och_riktlinjer : Ägarformer och riktlinjer
utformning_och_innehall : Utformning och innehåll
forslag_pa_verksamhetsformer : Förslag på verksamhetsformer
anvandning_av_tillfalligt_oanvanda_lokaler : Användning av tillfälligt oanvända lokaler
utokat_uppdrag_for_existerande_institutioner : Utökat uppdrag for existerande institutioner
allmanna_kontor_som_politisk_fraga : Allmänna kontor som politisk fråga
naringsliv : Näringsliv
